CXX = g++
CXX_FLAGS = -Wall
OUTEXT = .out

all:
	$(CXX) $(CXX_FLAGS) -o polyexam$(OUTEXT) poly0.cpp polyexam0.cpp
	$(CXX) $(CXX_FLAGS) -o polytest$(OUTEXT) poly0.cpp polytest0.cpp
clean:
	rm -r $(OUTFILE)